default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: eco-box_development 

test:
  <<: *default
  database: eco-box_test

production:
  <<: *default
  database: eco-box_production
  username: eco-box_app
  password: eco-box